### ISSUE TITLE
Configuration Support

### ISSUE THREAD

**Issue by jaxxstorm** [jaxxstorm/unseal#1]
One of the key features is the ability to unlock multiple vaults in one go, using multiple different keys.

Support a configuration file which allows users to specify a site, as well as the type of unseal key (whether it be GPG, standard etc) as well as an array of hostnames which should be checked/unlocked. Something like:

```
dev:
  type: GPG
  hosts:
    - vault1
    - vault2

prod:
  type: keybase
  hosts:
    - vault3
    - vault4
```

Would be ideal
