### ISSUE TITLE
GPG support

### ISSUE THREAD

**Issue by jaxxstorm** [jaxxstorm/unseal#3]
Currently we are prompted for the key, which gives us no benefit over the standard Vault command line tool.

Add support for GPG to the config file! This way, we can specify the path to GPG keys during usage, and it can automagically unlock the GPG keyring and grab the token.

**Comment by jaxxstorm** [comment]
Currently, the config file looks like this:
```
hosts:
  - name: vault0
    port: 8200
    key: my_key
  - name: vault2
    port: 8200
    key: prompt
  - name: vault1
    port: 8200
    key: prompt
  - name: vault3
    port: 8200
    key: a2V5Cg==
```

In order to make use of different key types, we _probably_ need to make key an array?
